@startuml

!function $comment()
!return ""
!endfunction
:Вход;
note right
Тестовый вариан вычислений
Локальные переменные:
L0: UInt32 - Переменная 1
L1: UInt32 - Переменная 2
L2: UInt32 - Переменная 3
L3: UInt32 - Переменная 4
L4: UInt32[5] - Массив 1
L5: UInt32 - Переменная 6
L6: UInt32 - Переменная 7
L0: UInt32 - Переменная 8
end note

:Единичное вычисление\nL0 = 123 + 5]
:L0 = 123 + 5]

:Вычисление1\nL0 = 123 + 5\n$comment()Вычисление 2\nL0 = L0]


:Множественное вычисление\nL1 = 123 + L0\nL0 = L1 * 2]
:L1 = 123 + L0\nL0 = L1 * 2]

:Раскрытие\nL0 = 0\n...\nL3 = 0]
:Раскрытие\nL4[0...4] = 0]

:L0 = 0\n...\nL3 = 0]
:L4[0...4] = 0]

:L0 = 5\nL1 = 0\n...\nL3 = 0\nL5 = 1\n...\nL7 = 1]

:Выход;
@enduml