@startuml

!function $comment()
!return ""
!endfunction
:Вход;
note right
Тестовый вариан if
Локальные переменные:
L0: UInt32 - Локальная переменная
end note

if (Локальная переменная равна 0?\nL0 == 0) then (да)
    'Действие 1
else (нет)
    'Действие 2
endif

if (Локальная переменная равна 0?\nL0 ==\n0) then (да)
    'Действие 1
else (нет)
    'Действие 2
endif

if (Локальная переменная равна 0?L0 == 0) then (да)
    'Действие 1
else if (Локальная 
переменная равна 1?L0 == 1) then (да)
    'Действие 2
elseif (Локальная 
переменная равна 2?
L0 == 2) then (да)
    'Действие 2
else (нет)
    'Действие 5
endif


:Выход;
@enduml