@startuml

!function $comment()
!return ""
!endfunction
:Вход;
note right
Тестовый вариан Функций
Локальные переменные:
L0: UInt32 - Вход 1
L1: UInt32 - Вход 2
L2: UInt32 - Возврат 1
L3: UInt32 - Возврат 2
end note

:Единичный вызов\n"Функция_1\n(L0) -> ()"|
:"Функция_2\n(L0) -> (L2)"|
:"Функция_3\n() -> (L1)"|
:"Функция_4\n(L0) -> (L1, L2)"|
:"Функция_5"|

:Вызов_1"Функция_1(L0) -> ()"
Вызов_2"Функция_2(L0) -> (L1)"
$comment()Вызов_3"Функция_3() -> (L1)"|

:"Функция_4\n(L0) -> (L1, L2)""Функция_4\n(L0) -> (L1, L2)""Функция_4(L0) -> (L1, L2)"|
:"Функция_5"\n"Функция_5"|


:Выход;
@enduml